### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mikelmb1** [thedev132/Osintgram#4]
I get this error and i can't lauch it. Can someone help please?
(venv) PS C:\Users\marti\Osintgram> python main.py xxxxxxxxxxxxx
Traceback (most recent call last):
  File "C:\Users\marti\Osintgram\main.py", line 90, in <module>
    pyreadline.Readline().parse_and_bind("tab: complete")
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marti\Osintgram\venv\Lib\site-packages\pyreadline\rlmain.py", line 422, in __init__
    BaseReadline.__init__(self)
  File "C:\Users\marti\Osintgram\venv\Lib\site-packages\pyreadline\rlmain.py", line 62, in __init__
    mode.init_editing_mode(None)
  File "C:\Users\marti\Osintgram\venv\Lib\site-packages\pyreadline\modes\emacs.py", line 633, in init_editing_mode
    self._bind_key('space',       self.self_insert)
  File "C:\Users\marti\Osintgram\venv\Lib\site-packages\pyreadline\modes\basemode.py", line 162, in _bind_key
    if not callable(func):
           ^^^^^^^^^^^^^^
  File "C:\Users\marti\Osintgram\venv\Lib\site-packages\pyreadline\py3k_compat.py", line 8, in callable
    return isinstance(x, collections.Callable)
                         ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Callable'

**Comment by thedev132** [comment]
I’ll take a look at it. Sorry I didn’t notice it because I am running it on Mac and Linux not Windows.

**Comment by thedev132** [comment]
Ok so it seems the package pyreadline is outdated by fortunately someone made an up to date version called pyreadline3. I just pushed the changes to the repo so just run `git pull` and it should run.

**Comment by thedev132** [comment]
I went back and it seems that the script exits by itself after login. You could try disabling pyreadline by just changing the `is_windows = True` in main.py (line 15)

**Comment by thedev132** [comment]
I went back and still saw the script exit after login. In the meantime, you can comment out any lines with pyreadline and it will work fine

**Comment by mikelmb1** [comment]
> I went back and still saw the script exit after login. In the meantime, you can comment out any lines with pyreadline and it will work fine

I commented the lines with pyredline and its working now Thanks!

**Comment by thedev132** [comment]
I removed the readline library as the script works perfectly without it (it was for tab autocomplete). I'm looking into reprogramming it but its not my main priority right now. (restoring most of the commands is)
