### ISSUE TITLE
AttributeError: 'Osintgram' object has no attribute '__get_feed__'

### ISSUE THREAD

**Issue by Aradhya-Shaswat** [thedev132/Osintgram#5]
Got this error while running any command that requires searching through the target's profile. Except few commands like info.

**Comment by thedev132** [comment]
Did you check the ReadMe to see if the command is supported? I'm trying to support more commands.

**Comment by Aradhya-Shaswat** [comment]
Oh wait my bad. Thank's for clarifying tho. I will suggest disable the option in the main tool like grey it out or add COMING SOON.

**Comment by thedev132** [comment]
Thanks for the advice! I will make sure to clarify that
